name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: python-wasm-builder prepare
      run: |
            WD=$(pwd)
            python3 -V
            echo $WD
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
            sudo apt-get update
            # git clang libffi-dev libssl-dev zlib1g-dev libncursesw5-dev make
            sudo apt-get install -y bash wget
            cd $GITHUB_WORKSPACE
            time bash ./python-wasm-sdk.sh

    - name: Package SDK
      uses: actions/upload-artifact@v2
      with:
        name: sdk
        path: $GITHUB_WORKSPACE/sdk
